.github/workflows/release.yml
Release only when there are modifications in fwk (modify the release.yml)
**Checklist**
=> chore: release only when there are modifications in fwk

.github/workflows/release.yml
manual merge (triggered in the Github actions)
**Checklist**
=> chore: manual release

framework/API.md, framework/src/processing/spark-runtime/emr-serverless/spark-emr-runtime-serverless.ts, framework/test/unit/processing/spark-runtime-serverless.test.ts
=> fix: Allow no policy for SparkEmrServerlessRuntime.createExecRole()

framework/test/resources/processing/pyspark-application-package/Dockerfile, website/docs/constructs/library/pyspark-application-package.md
#184
update the docs to use AL2023 when we provide a Dockerfile definition
**Checklist**
=> docs: upgrade docs to use al2023

framework/API.md, framework/src/processing/cicd-pipeline/spark-emr-cicd-pipeline.ts, framework/test/e2e/spark-cicd-pipeline.e2e.test.ts, framework/test/unit/nag/processing/nag-spark-cicd-pipeline.test.ts, framework/test/unit/processing/spark-cicd-pipeline.test.ts, website/docs/constructs/library/spark-cicd-pipeline.md
* delete previously retained SparkCICDPipeline resources #174 
* fix git remote add command
**Checklist**
=> fix: fix SparkCICDPipeline issues

.github/workflows/_build.yml, .projenrc.ts, framework/.projen/tasks.json, framework/API.md, framework/README.md, framework/package.json, framework/rosetta/default.ts-fixture, framework/rosetta/imports-only.ts-fixture, framework/src/governance/README.md, framework/src/governance/data-catalog-database.ts, framework/src/governance/data-lake-catalog.ts, framework/src/processing/cicd-pipeline/spark-emr-cicd-pipeline.ts, framework/src/processing/spark-job/pyspark-application-package.ts, framework/src/processing/spark-job/spark-job-emr-eks.ts, framework/src/processing/spark-job/spark-job-emr-serverless.ts, framework/src/processing/spark-job/spark-job.ts, framework/src/processing/spark-runtime/emr-serverless/README.md, framework/src/processing/spark-runtime/emr-serverless/spark-emr-runtime-serverless.ts, framework/src/storage/README.md, framework/src/storage/access-logs-bucket.ts, framework/src/storage/analytics-bucket.ts, framework/src/storage/data-lake-storage.ts, framework/src/utils/application-stack-factory.ts
- Fix examples in code
- Validate examples with `jsii-rosetta`
**Checklist**
=> fix: code examples and enforce validation at build

examples/spark-data-lake/README.md
Update the version of the ADSF lib in the example to match the latest one 
**Checklist**
=> fix: update adsf lib version to rc2 in the example

.projenrc.ts, framework/.projen/deps.json, framework/.projen/tasks.json, framework/API.md, framework/package.json, framework/src/processing/spark-runtime/emr-serverless/spark-emr-runtime-serverless.ts
- Add a check on the release label passed to `SparkEmrServerlessRuntime`
- Expose the CfnApplication object
-
**Checklist**
=> feat: add a check on the version emr passed to SparkEmrServerlessRuntime

framework/API.md, framework/src/governance/data-catalog-database.ts, framework/src/governance/data-lake-catalog.ts, framework/src/processing/cicd-pipeline/spark-emr-cicd-pipeline.ts, framework/src/processing/spark-job/pyspark-application-package.ts, framework/src/processing/spark-job/spark-job-emr-eks.ts, framework/src/processing/spark-job/spark-job-emr-serverless.ts, framework/src/processing/spark-job/spark-job.ts, framework/src/processing/spark-runtime/emr-serverless/spark-emr-runtime-serverless.ts, framework/src/storage/data-lake-storage.ts, framework/src/utils/vpc-helper.ts, framework/test/e2e/data-lake-storage.e2e.test.ts, framework/test/e2e/spark-job.e2e.test.ts, framework/test/e2e/spark-serverless-runtime.e2e.test.ts, website/docs/constructs/_category_.json, website/docs/constructs/cookbook.md, website/docs/constructs/customize.md
Modify all the constructs to expose the AWS resources created and allow for CDK escape hatches. 
Add documentation on how to customize constructs
**Checklist**
* [] Update tests
=> feat: expose all resources in constructs and add doc for customization

README.md, website/docusaurus.config.js
=> docs: rename project

framework/src/processing/lib/spark-job/spark-job.ts, framework/test/e2e/spark-job.e2e.test.ts
=> fix: add loggroup name

framework/src/utils/lib/tracked-construct.ts
changed the regex to avoid duplication of description
**Checklist**
=> fix: tracked construct regex

.projenrc.ts, framework/.projen/tasks.json
=> fix: add rm file .jsii.tabl.json for doc generation

website/docs/intro.md
Added missing commas to the python tab.
Add missing commas to python tab in intro.md
**Checklist**
=> docs: Add missing commas to python tab in intro.md

.github/workflows/run-e2e-tests.yml
=> chore: update session expiry

.github/workflows/release.yml, framework/test/unit/utils/s3-data-copy.test.ts
This PR fixes the automatic examples upload on release. This was successfully tested on a fork.
**Checklist**
=> ci: Fix paths in example packaging

framework/src/processing/lib/spark-runtime/emr-containers/eks-karpenter-helpers.ts, framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-runtime.ts, framework/test/e2e/s3-data-copy.e2e.test.ts, framework/test/unit/processing/spark-runtime-containers.test.ts
This PR update the IAM policy used by karpenter.
**Checklist**
=> fix: update IAM policy for karpenter

.github/workflows/run-e2e-tests.yml, framework/test/e2e/data-catalog-database.e2e.test.ts, framework/test/e2e/data-lake-catalog.e2e.test.ts, framework/test/e2e/data-lake-storage.e2e.test.ts, framework/test/e2e/pyspark-application-package.e2e.test.ts, framework/test/e2e/s3-data-copy.e2e.test.ts, framework/test/e2e/spark-cicd-pipeline.e2e.test.ts, framework/test/e2e/spark-containers-runtime.e2e.test.ts, framework/test/e2e/spark-job.e2e.test.ts, framework/test/e2e/spark-serverless-runtime.e2e.test.ts
This PR propose a way to parallelize some e2e tests to reduce the execution time of e2e.
**Checklist**
=> ci: e2e changes

framework/src/processing/lib/spark-runtime/emr-containers/eks-cluster-helpers.ts
=> fix: add unique name for launch template

.github/workflows/run-e2e-tests.yml
=> ci: change location of e2e exec

.github/workflows/on_pull_request_label.yml, LICENSE, framework/LICENSE
=> ci: add matrix to e2e on pull label

framework/test/e2e/spark-containers-runtime.e2e.test.ts
=> ci: increase e2e

.gitignore, .projen/tasks.json, .projenrc.ts, LICENSE, framework/LICENSE, package.json
rewrite the Apache-2.0 in a custom projen task to configure the copyright period and owner properly
**Checklist**
=> docs: configure proper license file

framework/src/utils/lib/resources/lambda/s3-data-copy/package.json
=> fix: remove ISC license mention in lambda code

framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-runtime.ts, framework/test/e2e/spark-containers-runtime.e2e.test.ts, framework/test/unit/processing/spark-runtime-containers.test.ts
=> fix: add security group creation

framework/test/resources/utils/lambda/my-cr/package-lock.json, framework/test/resources/utils/lambda/my-cr/package.json
=> chore: fix dependabot alert

website/docs/constructs/cookbook/compiled-documentation.md
Adding a chapter in the cookbook for troubleshooting the doc generation
**Checklist**
=> docs: troubleshooting documentation

framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-helpers.ts
=> chore: license header

.github/workflows/deploy_docs.yml
remove auto publish of new doc
**Checklist**
=> chore: remove auto publish of new doc

framework/package.json, framework/src/processing/README.md, framework/src/processing/examples/spark-job-emr-serverless.lit.ts, framework/src/storage/README.md, framework/src/storage/examples/data-lake-storage-objects-removal.lit.ts, framework/src/utils/README.md, framework/yarn.lock, website/docs/constructs/index.md, website/docs/constructs/library/03-Processing/03-spark-emr-serverless-job.mdx, website/docs/constructs/library/generated/_processing-spark-emr-runtime-serverless.mdx, website/docs/constructs/library/generated/_processing-spark-emr-serverless-job.mdx, website/docs/constructs/library/generated/_storage-analytics-bucket.mdx, website/docs/constructs/library/generated/_storage-data-lake-storage.mdx, website/docs/constructs/library/generated/_utils-data-vpc.mdx, website/docs/intro.md, yarn.lock
=> docs: review fixes

framework/src/consumption/README.md, website/docs/constructs/library/05-Consumption/03-athena-workgroup.mdx, website/docs/constructs/library/generated/_consumption-athena-workgroup.mdx
=> docs: add athena workdocs doc

website/docs/constructs/library/05-Consumption/03-athena-workgroup.mdx
=> docs: fix athena section

.github/workflows/release.yml
=> ci: update github action for release

framework/src/utils/README.md, framework/src/utils/lib/dsf-provider.ts, framework/test/unit/utils/dsf-provider.test.ts, website/docs/constructs/library/generated/_utils-custom-resources.mdx, website/docs/constructs/library/generated/_utils-customization.mdx, website/docs/constructs/library/generated/_utils-data-vpc.mdx, website/docs/constructs/library/generated/_utils-s3-data-copy.mdx
improve DsfProvider lambda invokation by adding a resource policy to lambda.
**Checklist**
=> fix: improve DsfProvider lambda invokation

framework/src/consumption/lib/resources/RedshiftDataExecution/index.mjs
implement status check in `RedshiftData` construct when providing a `deleteSql`
**Checklist**
=> fix: implement status check in Redshift Data API for deleteSql

examples/package-examples.sh
Update the package-example.sh script used in the release Github action to release examples
**Checklist**
=> fix: update github action for releasing examples

.github/workflows/release.yml
=> ci: Update release.yml to remove pre-release tag

website/docs/constructs/library/05-Consumption/04-opensearch-cluster.mdx
Add a link in the general documentation to the OpenSearch Cluster generated doc
**Checklist**
=> fix: add link to OpenSearch cluster generated doc

framework/src/consumption/lib/opensearch/opensearch.ts, framework/src/utils/lib/dsf-provider.ts, framework/test/unit/consumption/redshift-data.test.ts, framework/test/unit/nag/consumption/nag-opensearch.test.ts, framework/test/unit/nag/consumption/nag-redshift-data.test.ts, framework/test/unit/nag/consumption/nag-redshift-serverless.test.ts, framework/test/unit/nag/processing/nag-spark-runtime-containers.test.ts, framework/test/unit/nag/utils/nag-dsf-provider.test.ts, framework/test/unit/nag/utils/nag-s3-data-copy.test.ts, framework/test/unit/utils/dsf-provider.test.ts
change the scope of the DSFprovider to allow multiple provider per construct
**Checklist**
=> fix: dsfprovider scope

framework/src/consumption/README.md, website/docs/constructs/library/generated/_consumption-redshift-serverless-workgroup.mdx
A minor typo in the documentation.
**Checklist**
=> fix: correct typo in documentation

examples/spark-data-lake/infra/stacks/application_stack.py
=> docs: update example to use S3DataCopy

.github/workflows/on_pull_request_label.yml, .github/workflows/run-e2e-tests.yml
This PR update the gh action for e2e test to run streaming module
**Checklist**
=> ci: add streaming to e2e test

.github/workflows/on_pull_request_label.yml, .github/workflows/run-e2e-tests.yml
Bump some github actions that are using node 16 
**Checklist**
=> ci: bump actions in e2e gh action

.github/workflows/on_pull_request_label.yml, .github/workflows/run-e2e-tests.yml
some github actions were not bumped in previous PR
**Checklist**
=> ci: bump rest of gh actions

framework/API.md, framework/src/utils/lib/data-vpc-props.ts, framework/src/utils/lib/data-vpc.ts, framework/test/unit/consumption/opensearch.test.ts, framework/test/unit/utils/data-vpc.test.ts
Introduce a new props to change the number of NATs created by the DataVpc.
**Checklist**
=> feat: Allow number of NAT to DataVpc

framework/src/consumption/lib/opensearch/opensearch.ts
temporary workaround as suggested here 
https://github.com/aws/aws-cdk/issues/29891
=> fix: aws custom resource sdk bug

framework/test/e2e/kafka-api.e2e.test.ts
=> fix(kafka-api): Correction e2e

website/docusaurus.config.js, website/src/pages/index.js
=> docs: Add api reference in website

website/docs/constructs/cookbook/compiled-documentation.md, website/docs/constructs/cookbook/construct-design.md, website/docs/constructs/cookbook/contributing.md, website/docs/constructs/cookbook/custom-resources.mdx, website/docs/constructs/cookbook/tracked-construct.md
Add guide for contributing to the framework
**Checklist**
=> docs: add contributing guidelines

framework/API.md, framework/src/streaming/lib/msk/msk-utils.ts, framework/src/streaming/lib/msk/resources/lambdas/tlsCrudAdminClient/topic-crud.mjs, framework/test/e2e/msk-provisioned-tls.e2e.test.ts
=> feat(kafka-api): Add support for configEntries

examples/spark-data-lake/README.md, examples/spark-data-lake/infra/app.py, examples/spark-data-lake/infra/stacks/application_stack.py
fix minor issues with the spark data lake example
**Checklist**
=> fix: spark data lake readme

framework/API.md, framework/src/streaming/README.md, framework/src/streaming/lib/msk/msk-provisioned.ts, framework/src/streaming/lib/msk/msk-utils.ts, framework/src/streaming/lib/msk/resources/lambdas/crudIam/topic-crud.mjs, framework/src/streaming/lib/msk/resources/lambdas/tlsCrudAdminClient/topic-crud.mjs, framework/test/e2e/msk-provisioned-kraft.e2e.test.ts, framework/test/unit/streaming/msk-provisioned.test.ts, website/docs/constructs/library/generated/_streaming-msk-provisioned.mdx, website/docs/constructs/library/generated/_streaming-msk-serverless.mdx
Closes #640 
Based on the MSK version, we create the Zookeeper infrastructure when required. 
**Checklist**
=> feat: msk 3.7.X support

framework/generate_doc.mjs, website/docs/constructs/library/generated/_consumption-athena-workgroup.mdx, website/docs/constructs/library/generated/_consumption-opensearch.mdx, website/docs/constructs/library/generated/_consumption-redshift-data-sharing.mdx, website/docs/constructs/library/generated/_consumption-redshift-serverless-namespace.mdx, website/docs/constructs/library/generated/_consumption-redshift-serverless-workgroup.mdx, website/docs/constructs/library/generated/_governance-data-catalog-database.mdx, website/docs/constructs/library/generated/_governance-data-lake-catalog.mdx, website/docs/constructs/library/generated/_processing-pyspark-application-package.mdx, website/docs/constructs/library/generated/_processing-spark-cicd-pipeline.mdx, website/docs/constructs/library/generated/_processing-spark-emr-runtime-containers.mdx, website/docs/constructs/library/generated/_processing-spark-emr-runtime-serverless.mdx, website/docs/constructs/library/generated/_processing-spark-emr-serverless-job.mdx, website/docs/constructs/library/generated/_storage-access-logs-bucket.mdx, website/docs/constructs/library/generated/_storage-analytics-bucket.mdx, website/docs/constructs/library/generated/_storage-data-lake-storage.mdx, website/docs/constructs/library/generated/_streaming-kafka-api.mdx, website/docs/constructs/library/generated/_streaming-msk-provisioned.mdx, website/docs/constructs/library/generated/_streaming-msk-serverless.mdx, website/docs/constructs/library/generated/_utils-custom-resources.mdx, website/docs/constructs/library/generated/_utils-customization.mdx, website/docs/constructs/library/generated/_utils-data-vpc.mdx, website/docs/constructs/library/generated/_utils-s3-data-copy.mdx, website/docs/intro.md, website/docusaurus.config.js, website/package.json, website/yarn.lock
bump version of `docusaurus` used in github page from 2.4 to 3.4 .
**Checklist**
=> chore: bump docusaurus

framework/yarn.lock
=> chore: fix dependabot alerts

framework/API.md, framework/src/streaming/README.md, framework/src/streaming/examples/msk-provisioned-cluster-policy.lit.ts, framework/src/streaming/examples/msk-serverless-bring-vpc.lit.ts, framework/src/streaming/examples/msk-serverless-cluster-policy.lit.ts, framework/src/streaming/examples/msk-serverless-default.lit.ts, framework/src/streaming/lib/msk/msk-helpers.ts, framework/src/streaming/lib/msk/msk-provisioned.ts, framework/src/streaming/lib/msk/msk-serverless.ts, framework/test/e2e/msk-provisioned-iam.e2e.test.ts, framework/test/e2e/msk-serverless.e2e.test.ts, framework/test/unit/streaming/msk-serverless.test.ts, website/docs/constructs/library/generated/_streaming-msk-provisioned.mdx, website/docs/constructs/library/generated/_streaming-msk-serverless.mdx
Add a method in msk provisioned and serverless constructs to add msk cluster policy IAM policy.
**Checklist**
=> feat(msk): Add msk cluster policy method

framework/test/unit/processing/spark-cicd-pipeline.test.ts
remove the detailed logs from the `SparCicdPipeline` tests
**Checklist**
=> fix: remove console logs for spark CICD tests

website/docs/constructs/known_issues.md
#692 
Add a known issues page in the github page documentation
**Checklist**
=> docs(website): Add a known issue section in github page documentation

framework/src/processing/lib/spark-runtime/emr-containers/eks-karpenter-helpers.ts
=> fix(emr-containers): fix iam policy for karpenter

framework/API.md, framework/src/consumption/README.md, framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-namespace-props.ts, framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-namespace.ts, framework/src/utils/lib/create-service-linked-role.ts, framework/src/utils/lib/index.ts, framework/test/unit/nag/consumption/nag-redshift-data-sharing.test.ts, framework/test/unit/nag/consumption/nag-redshift-serverless.test.ts, website/docs/constructs/library/generated/_consumption-redshift-serverless-workgroup.mdx, website/docs/intro.md
Get or create the Redshift service link role before creating Redshift resources
**Checklist**
=> fix(redshift): add Redshift SLR creation

website/docs/intro.md, website/package.json, website/yarn.lock
=> chore(deps): upgrade `path-to-regexp` to 0.1.10

framework/src/processing/lib/spark-runtime/emr-containers/eks-karpenter-helpers.ts
=> fix(processing): fix iam policy for karpenter

.github/workflows/release.yml
=> ci: bump github actions for checkout and setup-node to node20

framework/src/governance/lib/datazone/resources/datazone-gsr-msk-datasource/index.mjs
Fix an issue in the Lambda used by the MSK datazone data source
**Checklist**
=> fix(governance): msk data source lambda

.github/workflows/_build.yml, .github/workflows/_build_website.yml, .github/workflows/_store_deps_cache.yml, .github/workflows/deploy_docs.yml, .github/workflows/on_pull_request_label.yml, .github/workflows/on_workflows_change.yml, .github/workflows/release.yml, .github/workflows/run-e2e-tests.yml
=> ci: bump github actions to use node20

.github/workflows/release.yml
=> chore(deps): bump node version for download-artifact

website/yarn.lock
=> chore(deps):bump website deps

framework/API.md, framework/src/processing/lib/emr-releases.ts
=> fix(processing): Add latest EMR versions

.github/workflows/_build.yml, .github/workflows/release.yml
=> ci: Update github action to add hidden folders

.github/workflows/release.yml
fix github release action
**Checklist**
=> chore: github release action

website/package.json, website/yarn.lock
=> chore(deps): fix dependabot findings on /website

framework/API.md, framework/src/processing/examples/spark-emr-runtime-containers-default.lit.ts, framework/src/processing/examples/spark-emr-runtime-containers-execrole.lit.ts, framework/src/processing/examples/spark-emr-runtime-containers-grant-execution.lit.ts, framework/src/processing/examples/spark-emr-runtime-containers-interactive-endpoint.lit.ts, framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-runtime.ts, framework/test/e2e/spark-emr-containers.e2e.test.ts, framework/test/unit/nag/processing/nag-spark-runtime-containers.test.ts, framework/test/unit/processing/spark-runtime-containers.test.ts, website/docs/constructs/library/generated/_processing-spark-emr-runtime-containers.mdx
**Issue #841**
Correct S3-bucket name for policies in various files.
**Checklist**
=> chore(doc): Correct S3-bucket name

.github/workflows/deploy_docs.yml
=> chore(gh-actions):bump gh action to publish website

examples/spark-data-lake/infra/stacks/application_stack.py, examples/spark-data-lake/infra/stacks/cicd_stack.py, examples/spark-data-lake/infra/tests/test_example.py, examples/spark-data-lake/spark/Dockerfile, examples/spark-data-lake/spark/pyproject.toml, examples/spark-data-lake/spark/src/agg_trip_distance.py, examples/spark-data-lake/spark/test/test_agg_trip_distance.py
Upgrade the Spark data lake example:
* Bump the EMR version
* Bump Spark version and dependencies
* Update great_expectations code because of breaking change in v1.x
* Update permissions in the Spark execution role with new catalog update
**Checklist**
=> chore(example): bump EMR and Spark code

examples/spark-data-lake/infra/stacks/application_stack.py, examples/spark-data-lake/infra/stacks/cicd_stack.py, framework/.projen/tasks.json, framework/API.md, framework/src/processing/lib/cicd-pipeline/spark-emr-cicd-pipeline.ts, framework/src/processing/lib/resources/codebuild-trigger/index.mjs, framework/src/processing/lib/resources/codebuild-trigger/package-lock.json, framework/src/processing/lib/resources/codebuild-trigger/package.json, framework/src/utils/lib/application-stage.ts, framework/src/utils/lib/index.ts, framework/src/utils/lib/integration-test-stack.ts, framework/test/e2e/spark-cicd-pipeline.e2e.test.ts, framework/test/e2e/spark-cicd-userdefined-pipeline.e2e.test.ts, framework/test/unit/nag/processing/nag-spark-cicd-pipeline.test.ts, framework/test/unit/processing/integ-test.sh, framework/test/unit/processing/spark-cicd-pipeline.test.ts
Added support for cross-account integration test in the Spark CICD Construct
**Checklist**
=> feat: Support for Cross-Account Integration Test

website/package.json, website/yarn.lock
Update docusaurus and dependencies versions
**Checklist**
=> chore: bump docs versions

website/static/img/adsf-diagrams.drawio
Fix product names on some diagrams
**Checklist**
=> chore(doc): update names on diagrams
