examples/spark-data-lake/infra/cdk.context.json
examples/spark-data-lake/infra/stacks/application_stack.py

Fix the account information syntax in the example for cross account deployments.
Add removal policy to constructs part of the Application Stack 
**Checklist**

fix: fix account info in cdk context and add removal policy to constructs

---

framework/API.md
framework/src/processing/spark-job/spark-job-emr-serverless.ts
framework/test/e2e/spark-job.e2e.test.ts
framework/test/unit/processing/spark-job.test.ts

Added removalPolicy property to sparkSparkEmrServerlessJob
Updated unit tests.
**Checklist**

fix: sparkSparkEmrServerlessJob doesn’t provide the removal_policy parameter

---

.projenrc.ts
framework/.projen/tasks.json

Fix e2e tests that are not run by changing the `test:e2e` task to use jest directly
**Checklist**

fix: run e2e tests

---

framework/API.md
framework/src/governance/data-catalog-database.ts
framework/src/governance/data-lake-catalog.ts
framework/test/e2e/spark-job.e2e.test.ts
framework/test/unit/governance/data-catalog-database.test.ts

- Added table level property in `DataLakeCatalog`
- Default value of table level would now depend on the value of `locationPrefix` property

fix: `crawlerTableLevelDepth` Property in Catalog 

---

framework/test/e2e/spark-job.e2e.test.ts

The e2e test for the Spark Job construct is now deleting all resources because we leverage the `removalPolicy` parameter 
**Checklist**

fix: e2e test for spark job deleting all resources

---

framework/test/e2e/test-stack.ts

Avoid tracking deployments made for e2e tests (using the context variable `DISABLE_CONSTRUCTS_DEPLOYMENT_TRACKING`).
**Checklist**

test: do not track e2e tests deployments

---

framework/src/processing/spark-runtime/emr-serverless/spark-emr-runtime-serverless.ts

**Issue #, if available:** n/a
If a VPC is passed to the serverless construct, it still creates a KMS key that ends up being unused. This change only creates the KMS key when creating the VPC.
**Checklist**

fix: Only create the KMS key when creating the VPC.

---

.github/workflows/release.yml

This PR introduces the usage of an example artifact created during the release process. With that, the workflow can process and upload this artifact as a release asset.
**Checklist**

ci: Use examples artifact for release

---

framework/API.md
framework/src/governance/lib/data-catalog-database.ts
framework/src/processing/lib/spark-job/spark-job.ts
framework/src/utils/lib/bucket-utils.ts
framework/src/utils/lib/utils.ts
framework/src/utils/lib/vpc-helper.ts
framework/test/unit/governance/data-catalog-database.test.ts

Adds a method in `Utils` to generate a unique hash based on the scope of the CDK resource.
Change all `Names.uniqueResourceName` and `Names.uniqueId ` to this method.
**Checklist**

feat: add unique hash method

---

framework/API.md
framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-runtime.ts
framework/src/processing/lib/spark-runtime/emr-serverless/spark-emr-runtime-serverless.ts
framework/src/utils/README.md
framework/src/utils/examples/data-vpc-default.lit.ts
framework/src/utils/examples/data-vpc-flowlog.lit.ts
framework/src/utils/examples/data-vpc-removal.lit.ts
framework/src/utils/lib/data-vpc-props.ts
framework/src/utils/lib/data-vpc.ts
framework/src/utils/lib/index.ts
framework/test/unit/nag/utils/nag-data-vpc.test.ts
framework/test/unit/processing/spark-runtime-containers.test.ts
framework/test/unit/utils/data-vpc.test.ts
website/docs/constructs/library/05-Utils/01-data-vpc.mdx
website/docs/constructs/library/generated/_utils-data-vpc.mdx

Add a new construct for creating a standard VPC for data platforms including VPC flow logs in CLoudWatch log group and S3 VPC endpoint
**Checklist**

feat: DataVpc construct

---

framework/API.md
framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-runtime.ts

Modify the scope of `SparkEmrContainerRuntime` parameters from private to public for all AWS resources
**Checklist**

fix: change scope of SparkEmrContainerRuntime parameters

---

.github/workflows/on_pull_request_label.yml

This PR fixes the E2E test workflow that triggers the tests based on the label assignment. After introducing the E2E test parallelization in #325, the workflow fails due to a race condition inside of the parallel branches trying to assign/delete the labels. This PR separates the label assignment and the actual parallel test runs.
**Checklist**

ci: Fix label-based E2E test workflow

---

.projenrc.ts
examples/dsf-quickstart/.projen/tasks.json
examples/spark-data-lake/infra/.projen/tasks.json

This PR fixes an issue introduced in #191. There is a race condition on examples build that might sometimes cause the build to fail. The parallel building of examples tries to globally install CDK which sometimes results in a race condition. Instead of the global `npm install`, the `npx` execution method is now used.
**Checklist**

ci: Fix race condition in examples build

---

.github/workflows/on_pull_request_label.yml

This PR improves the E2E automated workflow. The missing 'testing' label doesn't cause the workflow to fail anymore. This is for the case a (failed) test job is re-run. In that case, the 'testing' label will be missing, so its absence shouldn't cause the whole workflow to fail.
**Checklist**

ci: Improve E2E completed label workflow

---

framework/eslint-local-rules/rules.ts

This PR implements a workaround for the custom ESLint rule `no-tokens-in-construct-id`.
The non-nullable `Type.symbol` property still can have `null` values, so this PR introduces an additional check that just ignores such cases (we cannot analyze further anyway).
**Checklist**

ci: ESLint workaround for missing symbols

---

.github/workflows/on_pull_request_label.yml
.github/workflows/run-e2e-tests.yml
framework/test/e2e/redshift-serverless.e2e.test.ts

Update the github action to run the e2e test for redshift and any consumption layer construct that will be added
**Checklist**

ci: fix github action for e2e

---

framework/src/consumption/lib/redshift-serverless/redshift-serverless-namespace.ts
framework/test/unit/consumption/redshift-serverless-namespace.test.ts

Give IAM permissions for creating the Redshift Serverless service linked role
**Checklist**

fix: IAM role for redshift namespace CR

---

framework/src/storage/lib/analytics-bucket.ts
framework/test/unit/storage/analytics-bucket.test.ts

Change default configuration for the bucket Key in the `AnalyticsBucket` construct
**Checklist**

fix: configure bucket key by default

---

framework/API.md
framework/src/governance/lib/data-catalog-database-props.ts
framework/src/governance/lib/data-catalog-database.ts
framework/test/unit/governance/data-catalog-database.test.ts

…tructure
fix permissions for Glue crawler in `DataCatalogDatabase` in the edge case of flat data lake structure
**Checklist**

fix: change permissions for Glue crawler in DataCatalogDatabase

---

framework/src/utils/lib/create-service-linked-role-props.ts
framework/src/utils/lib/create-service-linked-role.ts
framework/src/utils/lib/index.ts
framework/src/utils/lib/resources/lambda/create-service-linked-role/index.mjs
framework/src/utils/lib/resources/lambda/create-service-linked-role/package-lock.json
framework/src/utils/lib/resources/lambda/create-service-linked-role/package.json
framework/src/utils/lib/service-linked-role-service.ts
framework/test/e2e/create-service-linked-role.e2e.test.ts
framework/test/unit/nag/utils/nag-create-service-linked-role.test.ts
framework/test/unit/utils/create-service-linked-role.test.ts

Added ability to create service linked roles (or absorb the error if one already exists)
**Checklist**

feat: Create Service Linked Role utility

---

framework/API.md
framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-namespace-props.ts
framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-namespace.ts
framework/src/consumption/lib/redshift/resources/RedshiftServerlessNamespace/index.mjs
framework/test/unit/consumption/redshift-serverless-namespace.test.ts

Users can now configure Redshift Serverless to create a final snapshot when stack is deleted
**Checklist**

feat(redshift-serverless): Allow users to take a final snapshot before `RedshiftServerlessNamespace` is deleted

---

framework/API.md
framework/src/processing/lib/spark-runtime/emr-containers/eks-cluster-helpers.ts
framework/src/processing/lib/spark-runtime/emr-containers/emr-virtual-cluster-props.ts
framework/src/processing/lib/spark-runtime/emr-containers/resources/k8s/resource-management.yaml
framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-runtime.ts
framework/test/unit/processing/spark-runtime-containers.test.ts

Currently the Resourcequota and Limit range cause jobs to fail if they are run with the default pod template when using init/sidecar containers. This PR allow the user to opt-out of Resourcequota and Limit range set by default and address the issue by addition of limit range on memory.
**Checklist**

fix: fix resource quota issue in spark-containers

---

framework/test/e2e/spark-emr-containers.e2e.test.ts

Currently in e2e test if the stack for `spark-conatiners` fails and does not delete cleanly the subsqueent e2e test will fail because the EKS cluster has the same name.  This PR add a randomized name.
**Checklist**

test: add random eks name to e2e test

---

framework/API.md
framework/src/consumption/examples/redshift-data-sharing-cross-account.lit.ts
framework/src/consumption/examples/redshift-data-sharing-same-account.lit.ts
framework/src/consumption/examples/redshift-serverless-workgroup-bootstrap.lit.ts
framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-workgroup.ts
framework/test/e2e/redshift-data-sharing.e2e.test.ts
framework/test/e2e/redshift-serverless.e2e.test.ts
framework/test/unit/consumption/redshift-serverless-workgroup.test.ts
framework/test/unit/nag/consumption/nag-redshift-serverless.test.ts
website/docs/constructs/library/generated/_consumption-redshift-data-sharing.mdx
website/docs/constructs/library/generated/_consumption-redshift-serverless-workgroup.mdx

Streamlined Redshift Data API. Users can now run custom SQL directly from the `RedshiftServerlessWorkgroup`
**Checklist**

feat(redshift-workgroup): Users can now run custom SQL directly from the `RedshiftServerlessWorkgroup` construct

---

website/docs/intro.md

fix: Missing import for cdk construct in documentation
**Checklist**

fix: Missing import for cdk construct in documentation

---

framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-workgroup.ts

fix: Redshift JDBC Crawler is now able to read credentials stored in Secrets Manager

---

framework/src/streaming/lib/msk/msk-helpers.ts
framework/test/unit/streaming/kafka-api.test.ts

#676 
Adding missing IAM policy to be able to update properties on MSK topics
**Checklist**

fix: Adding missing IAM policy to be able to execute updates on MSK topics

---

framework/test/e2e/s3-data-copy.e2e.test.ts
framework/test/unit/streaming/msk-provisioned.test.ts

Currently the S3DataCopy e2e test is broken because the source bucket is no longer public. This PR change the source bucket used in S3DataCopy e2e test. This bucket is owned by account that runs e2e.
**Checklist**

chore(e2e): Change the source bucket used in S3DataCopy e2e test

---

examples/spark-data-lake/infra/stacks/application_stack.py

The current source bucket of the Spark Data Lake example is not public anymore, this PR change it to a bucket owned by AWS
**Checklist**

chore: change source bucket for Spark Data Lake example

---

framework/test/unit/streaming/msk-provisioned.test.ts

Checking if no Custom Trigger used for Zookeeper is created in the template when a MSK cluster with KRaft mode is used
**Checklist**

test: Added another unit test on MSK 3.7 with KRaft

---

framework/API.md
framework/src/processing/lib/cicd-pipeline/spark-emr-cicd-pipeline.ts

The sparkcicd example that is published to construct hub was missing a parameter for the connection to source code repo. This PR add the parameter and the necessary imports.
**Checklist**
* [] Update tests

fix: add missing deps and code connection for git repo

---

framework/API.md
framework/src/streaming/lib/msk/msk-serverless.ts
framework/test/unit/nag/streaming/nag-streaming-msk-serverless.test.ts

#749 
Expose the bootstrap servers in the `MskServerless` construct
**Checklist**

fix(streaming): add bootstrap server for MskServerless

---

framework/API.md
framework/src/processing/lib/emr-releases.ts
framework/src/processing/lib/spark-runtime/emr-containers/resources/k8s/resource-management.yaml
framework/src/processing/lib/spark-runtime/emr-containers/resources/lambdas/managed-endpoint/index.mjs
framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-interactive-endpoint-props.ts
framework/src/processing/lib/spark-runtime/emr-containers/spark-emr-containers-runtime.ts

- fix an issue with limitrange on fluentd sidecar container
- standardize the default nodepools config types
- upgrade EMR version to 7.3 
**Checklist**

fix: EMR EKS limitrange, default nodepool configs and latest EMR version 

---

.github/workflows/release.yml
.projen/tasks.json
LICENSE
framework/LICENSE

Fix the release github action with the bumped version of Projen
**Checklist**

chore: fix release GitHub actions

---

framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-namespace.ts

Currently the [RedshiftServerlessNamespaceProps]https://github.com/awslabs/data-solutions-framework-on-aws/blob/main/framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-namespace-props.ts#L56-L60) defines a `adminUsername` property, but the [construct itself ignores it](https://github.com/awslabs/data-solutions-framework-on-aws/blob/main/framework/src/consumption/lib/redshift/redshift-serverless/redshift-serverless-namespace.ts#L134) and only uses a hardcoded default value of `admin`. This PR ensures the value is used when populated.
**Checklist**

fix: Ensure RedshiftServerlessNamespace uses adminUsername prop

---

examples/spark-data-lake/README.md
framework/API.md
framework/src/processing/README.md
framework/src/processing/lib/cicd-pipeline/spark-emr-cicd-pipeline.ts
framework/src/utils/lib/application-stage.ts
framework/test/e2e/spark-cicd-pipeline.e2e.test.ts
framework/test/e2e/spark-cicd-userdefined-pipeline.e2e.test.ts
framework/test/unit/nag/processing/nag-spark-cicd-pipeline.test.ts
framework/test/unit/processing/spark-cicd-pipeline.test.ts
website/docs/constructs/library/generated/_processing-spark-cicd-pipeline.mdx

**Issue #827**
Added support for user defined environments in CI/CD pipeline
**Checklist**

feat: User Defined Stages in Spark CI/CD Pipeline

---

examples/spark-data-lake/infra/stacks/application_stack.py

The spark data lake example needs to configure the EMR version accordingly to the dockerfile used to package the dependencies in the venv otherwise venv injection doesn't work. By default EMR is using 7.3 but the Spark code is using EMR 6 for packaging the dependencies into the venv
**Checklist**

chore: fix Spark data lake example by setting the EMR version

---

framework/src/governance/lib/custom-authorizer-environment-helpers.ts
framework/test/e2e/datazone-msk.e2e.test.ts

Fix the e2e tests for the streaming governance by updating the removal policy
**Checklist**

chore(tests): fix governance retention policy in e2e tests
